# Read SQL Data

In [34]:
import psycopg2
from psycopg2 import sql
from dotenv import load_dotenv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
# Load environment variables from the .secrets file
load_dotenv(".secrets")

True

## Initialize SQL connection

In [35]:
# Database connection parameters from environment variables
DB_NAME = os.getenv("AWS_RDS_DBNAME")
USER = os.getenv("AWS_RDS_USERNAME")
PASSWORD = os.getenv("AWS_RDS_PASSWORD")
HOST = os.getenv("AWS_RDS_HOST")
PORT = os.getenv("AWS_RDS_PORT")

# Connect to PostgreSQL database
conn = psycopg2.connect(
    dbname=DB_NAME,
    user=USER,
    password=PASSWORD,
    host=HOST,
    port=PORT
)
cur = conn.cursor()
conn

## Read data

In [ ]:
# Query the data
query = """
    SELECT *
    FROM dbt_lbassetti.base_pe_returns 
"""


data = pd.read_sql(query, conn)

# Close the connection
# conn.close()
data

C:\Users\Lorenzo\AppData\Local\Temp\ipykernel_17752\1813841347.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, conn)

,vintage_year,asset_class,geo_region,first_transaction_period,as_of_date,fund_count,irr_pooled,irr_equal_weighted,irr_capital_weighted,irr_average,...,tvpi_std_dev,dpi_pooled,dpi_capital_weighted,dpi_average,dpi_top_5,dpi_upper_quartile,dpi_median,dpi_lower_quartile,dpi_bottom_5,dpi_std_dev
0,1996,Buyout & Growth Equity,APAC,1996 Q1,2024-03-31,8.0,0.048338,0.004460,0.025856,-0.024306,...,0.613760,1.317590,1.256511,1.016255,1.853589,1.483729,0.844490,0.655950,0.288713,0.613760
1,1998,Buyout & Growth Equity,APAC,1998 Q1,2024-03-31,10.0,0.018771,0.026780,0.013794,0.036238,...,0.506711,1.086388,1.080748,1.129784,1.709503,1.614811,1.075143,0.771166,0.449256,0.506711
2,1999,Buyout & Growth Equity,APAC,1999 Q1,2024-03-31,9.0,0.099353,0.130679,0.109944,0.167163,...,1.300974,1.718189,1.746681,1.976349,3.984427,2.830999,1.544177,1.126494,0.728574,1.302451
3,2000,Buyout & Growth Equity,APAC,2000 Q1,2024-03-31,8.0,0.195697,0.159198,0.195583,0.165773,...,1.159237,2.347237,2.439875,1.926944,3.700119,2.146291,1.738425,1.457282,0.668606,1.190044
4,2001,Buyout & Growth Equity,APAC,2001 Q2,2024-03-31,9.0,0.196524,0.186182,0.196417,0.170202,...,1.063339,2.392492,2.276125,2.065716,3.747900,2.283240,1.955181,1.433690,0.880326,1.063492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,2023,Venture Capital,US,2023 Q1,2024-03-31,55.0,0.030862,-0.057749,-0.033280,-0.131058,...,0.177129,0.000031,0.000042,0.000103,0.000000,0.000000,0.000000,0.000000,0.000000,0.000763
328,2023,Buyout & Growth Equity,US,2023 Q1,2024-03-31,41.0,0.145259,-0.016260,0.124777,-0.027422,...,0.412742,0.012678,0.012375,0.020406,0.058155,0.000000,0.000000,0.000000,0.000000,0.079192
329,2023,Subordinated Capital & Distressed,US,2023 Q1,2024-03-31,11.0,0.239877,0.253213,1.601510,0.129261,...,0.399433,0.018359,0.019396,0.021911,0.073954,0.036922,0.005760,0.000000,0.000000,0.032536
330,2023,Real Estate,US,2023 Q1,2024-03-31,11.0,-0.148758,0.034740,-0.193510,-0.125276,...,0.284615,0.005047,0.010614,0.011331,0.062319,0.000000,0.000000,0.000000,0.000000,0.029831
331,2023,Fund of Funds & Secondary Funds,US,2023 Q1,2024-03-31,11.0,0.675979,0.496926,0.613859,0.555816,...,0.745239,0.015945,0.013054,0.001637,0.009003,0.000000,0.000000,0.000000,0.000000,0.005429